# Jekyll Settings
markdown: kramdown
kramdown:
  use_coderay: true
pygments: true

# Site settings
version: "0.24"
url: http://google.github.io/truth
title: Truth
tagline: We've made failure a strategy
description: "A proposition/assertion framework for testing in Java"

# Navigation
navigation:
- text: Change
  url: /truth/changelog/
- text: Javadoc
  url: /truth/api/
- text: FAQ
  url: /truth/faq/
- text: Usage
  url: /truth/usage/
- text: Home
  url: /truth
