auto: true
url: "https://truth.dev"
baseurl: '/'
markdown: kramdown
repository: google/truth
version: "1.1.1"

title: Truth
tagline: Fluent assertions for Java and Android
description: "Fluent assertions for Java and Android"

themeColor: purple

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _site
  - node_modules
  - vendor

sass:
  style: compressed

googleAnalyticsId: UA-43772875-10

plugins:
  - jekyll-redirect-from

nav:
  - item:
      name: Home
      url: /
  - item:
      name: FAQ
      url: /faq
  - item:
      name: Javadoc
      url: /api/1.1.1/
  - item:
      name: Floating Point
      url: /floating_point
  - item:
      name: Fuzzy Truth
      url: /fuzzy
  - item:
      name: Proto Truth
      url: /protobufs
  - item:
      name: Compare
      url: /comparison
  - item:
      name: Supported Types
      url: /known_types
  - item:
      name: Extensions
      url: /extension
